version: "3.1"
recipe: default.v1
assistant_id: "restaurant_bot"
language: "vi"
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 200
    entity_recognition: True
    intent_classification: True
    constrain_similarities: True
    model_confidence: "softmax"
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.9
    ambiguity_threshold: 0.1
    fallback_intent_name: "fallback"

policies:
  - name: MemoizationPolicy
    max_history: 8
    priority: 3
  - name: RulePolicy
    core_fallback_threshold: 0.9
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true
    priority: 10
  - name: TEDPolicy
    max_history: 10
    epochs: 300
    batch_size: 64
    learning_rate: 0.001
    priority: 1
